const translations={
en:{
navServices:"Services",navProcess:"How it works",navCountries:"Countries",navFaq:"FAQ",navBook:"Book a consultation",
eyebrow:"UK & worldwide visa guidance",heroTitle:"Move forward with your visa journey.",heroText:"Clear, practical support for visa applications, document preparation and travel plans.",heroButton:"Start your enquiry",heroServices:"View services",heroNote:"No visa approval can be guaranteed. Final decisions are made by the relevant immigration authority.",
card1Title:"Practical guidance",card1Text:"From consultation to application preparation",card2Title:"Multilingual support",card2Text:"English · Polski · Lietuvių",card3Title:"Clear pricing",card3Text:"EUR and PLN examples",
stat1:"service areas",stat2:"languages",stat3:"destination regions",servicesEyebrow:"Services",servicesTitle:"Choose the support you need",
service1:"Initial consultation",service1Text:"Discuss your circumstances, route and application plan.",service2:"Tourist / Visitor",service2Text:"Guidance for short-term visits and supporting documents.",service3:"Student Visa",service3Text:"Application preparation and document guidance for study routes.",service4:"Work Visa",service4Text:"Support with work-related visa preparation and documentation.",service5:"Family & Residence",service5Text:"Guidance for family, residence and related applications.",service6:"Business Travel",service6Text:"Support for business visits and travel documentation.",service7:"Other Visa Needs",service7Text:"Tell us what you need and receive a tailored quotation.",customQuote:"Custom quote",priceNote:"Example prices — confirm your final prices before publishing.",
processEyebrow:"How it works",processTitle:"A simple process",step1Title:"Tell us about your case",step1Text:"Complete the short enquiry form.",step2Title:"Choose your service",step2Text:"Select the support you need.",step3Title:"Prepare your application",step3Text:"Work through documents and next steps.",
countriesEyebrow:"Destinations",countriesTitle:"Support for international travel",country1:"United Kingdom",country2:"United States",country3:"Canada",country4:"Schengen / Europe",country5:"Australia",country6:"New Zealand",country7:"UAE",country8:"Other destinations",
faqEyebrow:"FAQ",faqTitle:"Frequently asked questions",faq1Q:"Does your service guarantee visa approval?",faq1A:"No. Visa decisions are made by the relevant government or immigration authority. We help with preparation and process guidance.",faq2Q:"Can I use the service in Polish or Lithuanian?",faq2A:"Yes. The site supports English, Polish and Lithuanian.",faq3Q:"Can I pay online?",faq3A:"Yes, after a hosted payment provider or payment links are connected. Payments are not connected in this demo.",
contactEyebrow:"Start your enquiry",contactTitle:"Tell us what you need",contactText:"Complete the short form and we can follow up with the appropriate next steps.",contactNote:"Demo only: this form currently does not send or store submissions. Connect it to an email/CRM service before going live.",fullName:"Full name",email:"Email",phone:"Phone / WhatsApp",nationality:"Nationality",visaType:"Visa type",destination:"Destination",travelDate:"Intended travel date",message:"Message",submit:"Submit enquiry",footerText:"Visa guidance and application support.",footerDemo:"Replace demo contact details before publishing.",formSuccess:"Thank you. Your enquiry has been prepared. Connect this form to your email/CRM before going live."
},
pl:{
navServices:"Usługi",navProcess:"Jak to działa",navCountries:"Kraje",navFaq:"FAQ",navBook:"Umów konsultację",
eyebrow:"Doradztwo wizowe do Wielkiej Brytanii i innych krajów",heroTitle:"Sprawnie przejdź przez proces wizowy.",heroText:"Jasne i praktyczne wsparcie przy wnioskach wizowych, przygotowaniu dokumentów i planowaniu podróży.",heroButton:"Wyślij zapytanie",heroServices:"Zobacz usługi",heroNote:"Nie gwarantujemy uzyskania wizy. Ostateczną decyzję podejmuje właściwy organ imigracyjny.",
card1Title:"Praktyczne wsparcie",card1Text:"Od konsultacji do przygotowania wniosku",card2Title:"Obsługa wielojęzyczna",card2Text:"English · Polski · Lietuvių",card3Title:"Przejrzyste ceny",card3Text:"Przykładowe ceny w EUR i PLN",
stat1:"obszarów usług",stat2:"języki",stat3:"regionów podróży",servicesEyebrow:"Usługi",servicesTitle:"Wybierz potrzebne wsparcie",
service1:"Konsultacja wstępna",service1Text:"Omówienie Twojej sytuacji, wybranej ścieżki i planu aplikacji.",service2:"Wiza turystyczna / odwiedziny",service2Text:"Wsparcie przy krótkich pobytach i dokumentach.",service3:"Wiza studencka",service3Text:"Pomoc w przygotowaniu wniosku i dokumentów związanych ze studiami.",service4:"Wiza pracownicza",service4Text:"Wsparcie przy przygotowaniu dokumentów związanych z pracą.",service5:"Rodzina i pobyt",service5Text:"Wsparcie w sprawach rodzinnych, pobytowych i powiązanych.",service6:"Podróże służbowe",service6Text:"Wsparcie przy wyjazdach biznesowych i dokumentacji podróży.",service7:"Inne potrzeby wizowe",service7Text:"Opisz swoją sytuację, a przygotujemy indywidualną wycenę.",customQuote:"Wycena indywidualna",priceNote:"Ceny przykładowe — przed publikacją potwierdź ostateczny cennik.",
processEyebrow:"Jak to działa",processTitle:"Prosty proces",step1Title:"Opowiedz nam o swojej sytuacji",step1Text:"Wypełnij krótki formularz.",step2Title:"Wybierz usługę",step2Text:"Wskaż potrzebny zakres wsparcia.",step3Title:"Przygotuj wniosek",step3Text:"Przejdź przez dokumenty i kolejne kroki.",
countriesEyebrow:"Kierunki",countriesTitle:"Wsparcie w podróżach międzynarodowych",country1:"Wielka Brytania",country2:"Stany Zjednoczone",country3:"Kanada",country4:"Strefa Schengen / Europa",country5:"Australia",country6:"Nowa Zelandia",country7:"ZEA",country8:"Inne kierunki",
faqEyebrow:"FAQ",faqTitle:"Najczęściej zadawane pytania",faq1Q:"Czy gwarantujecie otrzymanie wizy?",faq1A:"Nie. Decyzję wizową podejmuje właściwy urząd lub organ imigracyjny. Pomagamy w przygotowaniu i wyjaśnieniu procesu.",faq2Q:"Czy mogę skorzystać z obsługi po polsku lub litewsku?",faq2A:"Tak. Strona obsługuje język angielski, polski i litewski.",faq3Q:"Czy mogę zapłacić online?",faq3A:"Tak, po podłączeniu zewnętrznego operatora płatności lub linków do płatności. W tej wersji płatności nie są jeszcze podłączone.",
contactEyebrow:"Wyślij zapytanie",contactTitle:"Powiedz nam, czego potrzebujesz",contactText:"Wypełnij krótki formularz, a skontaktujemy się w sprawie kolejnych kroków.",contactNote:"Wersja demonstracyjna: formularz obecnie nie wysyła ani nie zapisuje zgłoszeń. Przed uruchomieniem podłącz formularz do poczty lub CRM.",fullName:"Imię i nazwisko",email:"E-mail",phone:"Telefon / WhatsApp",nationality:"Obywatelstwo",visaType:"Rodzaj wizy",destination:"Kierunek",travelDate:"Planowana data podróży",message:"Wiadomość",submit:"Wyślij zapytanie",footerText:"Doradztwo wizowe i wsparcie przy przygotowaniu wniosków.",footerDemo:"Przed publikacją zastąp dane demonstracyjne właściwymi danymi kontaktowymi.",formSuccess:"Dziękujemy. Twoje zapytanie zostało przygotowane. Przed uruchomieniem podłącz formularz do poczty lub CRM."
},
lt:{
navServices:"Paslaugos",navProcess:"Kaip tai veikia",navCountries:"Šalys",navFaq:"DUK",navBook:"Užsakyti konsultaciją",
eyebrow:"Vizų konsultacijos į JK ir kitas šalis",heroTitle:"Lengviau pereikite vizos gavimo procesą.",heroText:"Aiški ir praktiška pagalba pildant vizų paraiškas, ruošiant dokumentus ir planuojant kelionę.",heroButton:"Pateikti užklausą",heroServices:"Peržiūrėti paslaugas",heroNote:"Vizos gavimas negarantuojamas. Galutinį sprendimą priima kompetentinga imigracijos institucija.",
card1Title:"Praktinė pagalba",card1Text:"Nuo konsultacijos iki paraiškos paruošimo",card2Title:"Pagalba keliomis kalbomis",card2Text:"English · Polski · Lietuvių",card3Title:"Aiškios kainos",card3Text:"Kainų pavyzdžiai EUR ir PLN",
stat1:"paslaugų sritys",stat2:"kalbos",stat3:"kelionių regionai",servicesEyebrow:"Paslaugos",servicesTitle:"Pasirinkite reikalingą pagalbą",
service1:"Pradinė konsultacija",service1Text:"Jūsų situacijos, kelionės tikslo ir paraiškos plano aptarimas.",service2:"Turistinė / lankytojo viza",service2Text:"Pagalba dėl trumpalaikių kelionių ir reikalingų dokumentų.",service3:"Studento viza",service3Text:"Pagalba ruošiant paraišką ir studijoms reikalingus dokumentus.",service4:"Darbo viza",service4Text:"Pagalba ruošiant su darbu susijusią vizos paraišką ir dokumentus.",service5:"Šeima ir gyvenamoji vieta",service5Text:"Pagalba šeimos, gyvenamosios vietos ir susijusiais klausimais.",service6:"Verslo kelionės",service6Text:"Pagalba dėl verslo kelionių ir kelionės dokumentų.",service7:"Kiti vizų poreikiai",service7Text:"Aprašykite savo situaciją ir gausite individualų pasiūlymą.",customQuote:"Individualus pasiūlymas",priceNote:"Kainų pavyzdžiai — prieš skelbdami patvirtinkite galutinį kainoraštį.",
processEyebrow:"Kaip tai veikia",processTitle:"Paprastas procesas",step1Title:"Papasakokite apie savo situaciją",step1Text:"Užpildykite trumpą užklausos formą.",step2Title:"Pasirinkite paslaugą",step2Text:"Nurodykite, kokios pagalbos reikia.",step3Title:"Paruoškite paraišką",step3Text:"Sutvarkykite dokumentus ir atlikite kitus žingsnius.",
countriesEyebrow:"Kryptys",countriesTitle:"Pagalba tarptautinėms kelionėms",country1:"Jungtinė Karalystė",country2:"Jungtinės Amerikos Valstijos",country3:"Kanada",country4:"Šengenas / Europa",country5:"Australija",country6:"Naujoji Zelandija",country7:"JAE",country8:"Kitos kryptys",
faqEyebrow:"DUK",faqTitle:"Dažniausiai užduodami klausimai",faq1Q:"Ar garantuojate vizos gavimą?",faq1A:"Ne. Sprendimą dėl vizos priima atitinkama vyriausybinė arba imigracijos institucija. Mes padedame pasiruošti ir suprasti procesą.",faq2Q:"Ar galiu naudotis paslauga lietuvių arba lenkų kalba?",faq2A:"Taip. Svetainė palaiko anglų, lenkų ir lietuvių kalbas.",faq3Q:"Ar galiu mokėti internetu?",faq3A:"Taip, prijungus išorinį mokėjimų operatorių arba mokėjimo nuorodas. Šioje demonstracinėje versijoje mokėjimai dar neprijungti.",
contactEyebrow:"Pateikite užklausą",contactTitle:"Papasakokite, ko jums reikia",contactText:"Užpildykite trumpą formą ir susisieksime dėl tolesnių veiksmų.",contactNote:"Demonstracinė versija: ši forma šiuo metu nesiunčia ir nesaugo užklausų. Prieš paleisdami prijunkite ją prie el. pašto arba CRM.",fullName:"Vardas ir pavardė",email:"El. paštas",phone:"Telefonas / WhatsApp",nationality:"Pilietybė",visaType:"Vizos tipas",destination:"Kelionės kryptis",travelDate:"Numatoma kelionės data",message:"Žinutė",submit:"Pateikti užklausą",footerText:"Vizų konsultacijos ir pagalba ruošiant paraiškas.",footerDemo:"Prieš publikuodami pakeiskite demonstracinius kontaktinius duomenis.",formSuccess:"Ačiū. Jūsų užklausa paruošta. Prieš paleisdami prijunkite formą prie el. pašto arba CRM."
}};

function setLanguage(lang){
 const t=translations[lang]||translations.en;
 document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(t[k]!==undefined)el.textContent=t[k]});
 document.documentElement.lang=lang;
 document.querySelectorAll("[data-lang]").forEach(b=>b.classList.toggle("active",b.dataset.lang===lang));
 localStorage.setItem("visa-language",lang);
}
document.querySelectorAll("[data-lang]").forEach(btn=>btn.addEventListener("click",()=>setLanguage(btn.dataset.lang)));
setLanguage(localStorage.getItem("visa-language")||"en");

document.getElementById("visaForm").addEventListener("submit",e=>{
 e.preventDefault();
 const lang=document.documentElement.lang||"en";
 document.getElementById("formMessage").textContent=translations[lang].formSuccess;
 e.target.reset();
});
document.getElementById("year").textContent=new Date().getFullYear();
